eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka1:8001/eureka/,http://admin:123123@eureka2:8002/eureka/,http://admin:123123@eureka3:8003/eureka/
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
feign:
  hystrix:  #熔断服务
    enabled: true
management:
  endpoints:
    web:
      exposure:
        # * 在yaml  文件属于关键字，所以需要加引号 ,Actuator只暴露了health和info端点 ,暴露所有端点
        include: "*"
  server:
    #port: ${healthport}
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      #查看详细的应用健康
      show-details: always
  info : 
    git : 
      mode : full
#hystrix dashboard的信息收集频率，默认500毫秒
hystrix : 
  stream : 
    dashboard : 
      intervalInMilliseconds: 5000
spring:
  zipkin :
    base-url : http://localhost:9411
  sleuth : 
    sampler : 
      percentage : 1